name: Java CI with Maven

on:
  push:
    branches: [ main ]
    paths:
      - 'PrjDep2/**'
      - 'PrjDep3/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'PrjDep2/**'
      - 'PrjDep3/**'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [PrjDep2, PrjDep3]
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Maven settings.xml
      run: |
          mkdir -p ~/.m2
          echo '<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ secrets.GITHUB_ACTOR }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./${{ matrix.project }}
  
    - name: List files after build
      run: ls -R ./${{ matrix.project }}/target
  
    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.project }}-jar
        path: ./${{ matrix.project }}/target/*.jar

    - name: Push JAR to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.run_number }}
        name: "${{ matrix.project }} Release ${{ github.run_number }}"
        files: ./${{ matrix.project }}/target/*.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to GitHub Packages
      run: mvn deploy -X
      working-directory: ./${{ matrix.project }}
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

    # - name: Check Dependencies
    #   uses: gregsdennis/dependencies-action@1.3.0
    #   env:
    #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# name: Java CI with Maven

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]
#   workflow_dispatch:

# permissions:
#   contents: write  # Required for creating releases
#   packages: write

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout Repository
#       uses: actions/checkout@v4

#     - name: Set up Maven settings.xml
#       run: |
#           mkdir -p ~/.m2
#           echo '<settings>
#             <servers>
#               <server>
#                 <id>github</id>
#                 <username>${{ secrets.GITHUB_ACTOR }}</username>
#                 <password>${{ secrets.GITHUB_TOKEN }}</password>
#               </server>
#             </servers>
#           </settings>' > ~/.m2/settings.xml

#     - name: Set up JDK 17
#       uses: actions/setup-java@v4
#       with:
#         java-version: '17'
#         distribution: 'temurin'
#         server-id: github
#         settings-path: ${{ github.workspace }}

#     - name: Build with Maven
#       run: mvn clean package
#       working-directory: ./PrjDep2
  
#     - name: List files after build
#       run: ls -R ./PrjDep2/target

#     - name: Upload JAR as Artifact
#       uses: actions/upload-artifact@v4
#       with:
#         name: my-java-app
#         path: ./PrjDep2/target/*.jar

#     - name: Push JAR to GitHub Releases
#       uses: softprops/action-gh-release@v1
#       with:
#         tag_name: ${{ github.run_number }}
#         name: "Dep Release ${{ github.run_number }}"
#         files: ./PrjDep2/target/*.jar
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#     - name: Publish to GitHub Packages
#       run: mvn deploy -X
#       working-directory: ./PrjDep2
#       env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  

#     - name: Check Dependencies
#       uses: gregsdennis/dependencies-action@1.3.0
#       env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
