name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write  # Required for creating releases
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Build with Maven
      run: mvn clean package
      working-directory: ./PrjDep2
  
    - name: List files after build
      run: ls -R ./PrjDep2/target

    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: my-java-app
        path: ./PrjDep2/target/*.jar

    - name: Push JAR to GitHub Releases
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.run_number }}
        name: "Dep Release ${{ github.run_number }}"
        files: ./PrjDep2/target/*.jar
      env:
        GITHUB_USERNAME: shuti491
        GITHUB_TOKEN: ${{ secrets.MYSECRET }}

    - name: Publish to GitHub Packages
      run: mvn deploy
      working-directory: ./PrjDep2
      env:
         GITHUB_USERNAME: shuti491
         GITHUB_TOKEN: ${{ secrets.MYSECRET }}  
